apiVersion: varroa.dev/v1
kind: PipelineTemplate
metadata:
  name: go-service
  displayName: Go service
  description: Echo a greeting parameter
spec:
  version: 2.1.3
  parameters:
    type: object
    additionalProperties: false
    properties:
      greeting:
        type: string
        default: "hello"
  jenkinsfile: |
    pipeline {
      agent { label 'smoke-a-default' }
      stages {
        stage('Greet') {
          steps {
            echo "template says: ${varroaParams.greeting}"
          }
        }
      }
    }
